---
title: "Setup Instructions for CANSSI Prairies Workshop 2025"
subtitle: "Processing and Forecasting with Epidemic Surveillance Data"
format: gfm
---

Welcome to the GitHub Repository for the CANSSI Prairies 2025 Workshop on Epi 
Surveillance. We've tried to make it easy 
for you to get started with this project, and we're happy to help! Please take 
your time and follow the steps below. If you encounter any issues or need extra 
help, feel free to reach out--our volunteers are available to assist during 
setup and throughout the workshop.

## 0. System requirements

We assume that you have [R](https://cran.rstudio.com) installed.

We also assume that you use [RStudio](https://posit.co/download/rstudio-desktop/).

If you're more familiar with a different IDE (VSCode, Emacs, etc.), that's fine

## 1. Download the repository (beginner option)

If you're new to GitHub or prefer not to use command-line tools, the easiest way
to get started is by downloading the repository as a ZIP file.

### Steps:
1. On the [CANSSI Prairies 2025 Workshop GitHub repository](https://github.com/dajmcdon/canssip-epidata-2025).
2. Click the green <kbd><> Code ▾</kbd> button located at the top right of this repository.
3. In the dropdown menu, select **Download ZIP**.
4. Once downloaded, extract the ZIP file to a folder on your local machine.
5. Open the extracted folder, and you’re all set!

You can now open the `epidata-workshop-2025.Rproj` file and start working 
with them.


## 1. Clone or fork the repository (advanced options)

If you're familiar with `git`, cloning or forking the repository is a more flexible
option. This will allow you to stay up to date with the latest changes and
contribute to the project directly. 


### Steps for cloning the repo:

The RStudio way:

1. On the [CANSSI Prairies 2025 Workshop GitHub repository](https://github.com/dajmcdon/canssip-epidata-2025).
1. Click the green <kbd><> Code ▾</kbd> button located at the top right of this repository.
1. Then in RStudio, choose "New project" > "Version Control" > "Git" and paste the address.
1. Choose a location on your machine where you want the files to be.
1. Select “Create Project”.

The Command Line way:

1. On the [CANSSI Prairies 2025 Workshop GitHub repository](https://github.com/dajmcdon/canssip-epidata-2025).
1. Click the green <kbd><> Code ▾</kbd> button located at the top right of this repository.
1. Open a terminal or command prompt on your computer.
1. Navigate to the folder where you want to store the project.
1. Run `git clone https://github.com/dajmcdon/canssip-epidata-2025.git`
1. Once cloning is complete, navigate into the project folder: `cd canssip-epidata-2025`


### Steps for forking the repo (requires a personal GitHub account):
1. In the top right corner of this GitHub repository, click the grey <kbd>⑂ Fork ▾</kbd> button.
2. Proceed from Step 2 in either the "Cloning" or even "Download Zip" options.
You'll just be working from your own remote copy rather our version of the materials.

## 2. Install required `R` packages

We will use a [lot]{.tertiary} of packages. Hopefully you only need the ones
listed below.

🤞 We hope this works... 🤞


In RStudio:

```{r}
#| eval: false
install.packages("remotes")
install.packages("tidyverse")
install.packages("tidymodels")
install.packages("glmnet")
remotes::install_github("cmu-delphi/epidatr")
remotes::install_github("cmu-delphi/epidatasets")
remotes::install_github("cmu-delphi/epiprocess@dev")
remotes::install_github("cmu-delphi/epipredict@dev")
remotes::install_github("dajmcdon/rtestim")
```


Ask for help if you get stuck.


## ✋ Getting help from our volunteers

If you encounter any issues or would like assistance with setting things up, 
don't hesitate to reach out. We're happy to help guide you through the process.
