---
---

\DeclareMathOperator*{\minimize}{minimize}

```{r setup}
#| include: false
options(htmltools.dir.version = FALSE)
primary <- "#002145"
secondary <- "#a41623"
tertiary <- "#f9c80e"
fourth_colour <- "#177245"
fifth_colour <- "#A393BF"
ubclblue <- "#6495ed"
theme_white <- "#fbfcff"
theme_black <- "#00162e"
colvec <- c(primary = primary, secondary = secondary,
            tertiary = tertiary, fourth_colour = fourth_colour,
            fifth_colour = fifth_colour, ubclblue = ubclblue)
library(epiprocess)
suppressMessages(library(tidyverse))
theme_update(legend.position = "bottom", legend.title = element_blank())
delphi_pal <- function(n) {
  if (n > 6L) warning("Not enough colors in this palette!")
  unname(colvec)[1:n]
}
scale_fill_delphi <- function(..., aesthetics = "fill") {
  discrete_scale(aesthetics = aesthetics, palette = delphi_pal, ...)
} 
scale_color_delphi <- function(..., aesthetics = "color") {
  discrete_scale(aesthetics = aesthetics, palette = delphi_pal, ...)
}
scale_colour_delphi <- scale_color_delphi
x <- archive_cases_dv_subset
x_latest <- epix_as_of(x, version = max(x$DT$version))
self_max = max(x$DT$version)
versions = seq(as.Date("2020-06-01"), self_max - 1, by = "2 weeks")
snapshots_all <- map_dfr(versions, function(v) { 
  epix_as_of(x, version = v) %>% mutate(version = v)}) %>%
  bind_rows(x_latest %>% mutate(version = self_max)) %>%
  mutate(latest = version == self_max)
snapshots <- snapshots_all %>% 
  filter(geo_value %in% c("ca", "fl"))
```

```{r, dev.args=list(bg=primary)}
#| include: false
#| label: cover-art
snapshots_all |>
  arrange(geo_value, version, time_value) |>
  ggplot(aes(x = time_value, y = percent_cli)) +  
  geom_line(
    aes(
      color = scale(as.numeric(interaction(version, geo_value))), 
      group = interaction(geo_value, version)
    )
  ) + 
  scale_x_date(minor_breaks = "month", labels = NULL, expand = expansion()) +
  labs(x = "", y = "") + 
  scale_y_continuous(expand = expansion(c(0, 0.05))) +
  theme_void() +
  scale_color_distiller(palette = "Set1", direction = 1) +
  theme(legend.position = "none", panel.background = element_blank())
```



## {background-image="gfx/cover-art-1.svg" footer=false}

::: {style="text-align:center; font-family:Gilda Display; font-size:1.8em; padding: 1em 0.5em; background-color: rgba(255, 255, 255, .5); backdrop-filter: blur(5px); box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .5);"}

[{{< meta talk-date >}}]{.primary style="font-size:0.75em;"}

[{{< meta talk-title >}}]{.primary style="font-size:1.25em;"}

[{{< meta talk-subtitle >}}]{.primary style="font-size:0.75em;"}

<br>

[{{< meta author >}}]{.primary}

:::

